INSERT INTO Sala (nom, adreca, municipi, num_columnes, num_files, te_mapa) VALUES
('Teatre Principal', 'Carrer de les Flors, 12', 'Barcelona', 20, 30, TRUE),
('Auditori Nacional', 'Avinguda de la Cultura, 5', 'Madrid', 25, 35, TRUE),
('Gran Teatre', 'Passeig de la Llum, 7', 'Valencia', 18, 25, FALSE),
('Cinema Imperial', 'Plaça Major, 3', 'Sevilla', 15, 20, TRUE),
('Palau de la Música', 'Carrer dels Sons, 1', 'Barcelona', 22, 32, TRUE),
('Sala de Concerts Renaixença', 'Avinguda del Mestre, 8', 'Bilbao', 19, 28, TRUE),
('Teatre Modern', 'Carrer Nou, 14', 'Zaragoza', 17, 22, FALSE),
('Cine Lumière', 'Boulevard des Arts, 9', 'Tarragona', 16, 24, TRUE),
('Auditori del Mar', 'Carrer de la Platja, 6', 'Malaga', 21, 33, TRUE),
('Sala Broadway', 'Avinguda del Teatre, 10', 'Murcia', 23, 34, FALSE),
('Teatre Clàssic', 'Carrer Antic, 11', 'Girona', 14, 18, TRUE),
('Opera Magna', 'Gran Via, 20', 'Madrid', 26, 38, TRUE),
('Cine Estrella', 'Rambla del Cinema, 2', 'Barcelona', 13, 17, FALSE),
('Sala Simfònica', 'Passeig de la Música, 3', 'Santander', 20, 30, TRUE),
('Amfiteatre Grec', 'Montjuïc, 15', 'Barcelona', 24, 36, FALSE),
('Sala Indie', 'Carrer Alternatiu, 5', 'Valencia', 12, 16, TRUE),
('Cinema Nova Era', 'Passeig de lEspectacle, 7', 'Granada', 18, 26, TRUE),
('Teatre Experimental', 'Carrer del Teatre, 4', 'Pamplona', 15, 21, FALSE),
('Palau d’Arts', 'Avinguda dels Compositors, 12', 'Alicante', 27, 40, TRUE),
('Sala Jazz Club', 'Carrer del Ritme, 8', 'Bilbao', 11, 15, FALSE);


INSERT INTO Event (tipus, nom, protagonista, descripcio, img_path, data_event, estat, sala_id) VALUES
('Concert', 'Rock Night', 'The Wild Ones', 'Una noche llena de rock clásico y moderno.', 'https://picsum.photos/200/200?random=1', '2025-03-10', 'Programado', 1),
('Teatro', 'Hamlet', 'Compañía Shakespeare', 'Una interpretación moderna de la clásica obra.', 'https://picsum.photos/200/200?random=2', '2025-04-15', 'Programado', 2),
('Cine', 'Inception', 'Leonardo DiCaprio', 'Proyección especial con comentarios del director.', 'https://picsum.photos/200/200?random=3', '2025-05-20', 'Confirmado', 3),
('Danza', 'Flamenco Pasión', 'Ballet Español', 'Una velada apasionante de flamenco y danza española.', 'https://picsum.photos/200/200?random=4', '2025-06-05', 'Confirmado', 4),
('Conferencia', 'Futuro de la IA', 'Dr. Susan Clarke', 'Una charla sobre inteligencia artificial y su impacto.', 'https://picsum.photos/200/200?random=5', '2025-07-10', 'Pendiente', 5),
('Exposición', 'Arte Moderno', 'Varios Artistas', 'Explorando las tendencias del arte contemporáneo.', 'https://picsum.photos/200/200?random=6', '2025-08-15', 'Confirmado', 6),
('Musical', 'Los Miserables', 'Elenco Original', 'Una de las obras más icónicas del teatro musical.', 'https://picsum.photos/200/200?random=7', '2025-09-25', 'Programado', 7),
('Stand-up', 'Comedia en Vivo', 'Carlos Ríos', 'Una noche de risas con el mejor humorista.', 'https://picsum.photos/200/200?random=8', '2025-10-05', 'Pendiente', 8),
('Ópera', 'La Traviata', 'Teatro Lírico Nacional', 'Una presentación inolvidable de la famosa ópera.', 'https://picsum.photos/200/200?random=9', '2025-11-15', 'Confirmado', 9),
('Taller', 'Fotografía Nocturna', 'Ana López', 'Aprende a capturar la belleza de la noche.', 'https://picsum.photos/200/200?random=10', '2025-12-10', 'Programado', 10),
('Feria', 'Gastronomía Internacional', 'Chefs Estrella Michelín', 'Un recorrido por sabores del mundo.', 'https://picsum.photos/200/200?random=11', '2026-01-20', 'Confirmado', 11),
('Jazz', 'Noche de Jazz', 'Blue Quartet', 'Jazz en vivo con los mejores músicos de la ciudad.', 'https://picsum.photos/200/200?random=12', '2026-02-15', 'Programado', 12),
('Festival', 'Cine Independiente', 'Directores Emergentes', 'Proyección de cortos y largometrajes.', 'https://picsum.photos/200/200?random=13', '2026-03-10', 'Pendiente', 13),
('Música', 'Tributo a Queen', 'We Will Rock You Band', 'Revive los mejores éxitos de Queen en vivo.', 'https://picsum.photos/200/200?random=14', '2026-04-05', 'Confirmado', 14),
('Exposición', 'Fotografía Urbana', 'Juan Pérez', 'Una mirada artística a la vida en la ciudad.', 'https://picsum.photos/200/200?random=15', '2026-05-20', 'Programado', 15),
('Danza', 'Ballet Clásico', 'Compañía Nacional de Danza', 'Las mejores piezas del ballet clásico.', 'https://picsum.photos/200/200?random=16', '2026-06-10', 'Pendiente', 16),
('Cine', 'El Padrino', 'Marlon Brando', 'Proyección especial del clásico del cine.', 'https://picsum.photos/200/200?random=17', '2026-07-15', 'Confirmado', 17),
('Conferencia', 'Explorando Marte', 'Dr. Ramón Torres', 'Los últimos descubrimientos sobre el planeta rojo.', 'https://picsum.photos/200/200?random=18', '2026-08-25', 'Programado', 18),
('Concierto', 'Pop Hits', 'Diana Gómez', 'Un concierto con los éxitos del pop actual.', 'https://picsum.photos/200/200?random=19', '2026-09-30', 'Pendiente', 19),
('Feria', 'Tecnología y Futuro', 'Innovadores Globales', 'Las últimas tendencias en tecnología.', 'https://picsum.photos/200/200?random=20', '2026-10-10', 'Confirmado', 20);